services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - docker=true # Slim Framework needs this for logging using php://stderr instead of file system
    volumes:
      - ./app:/app
    working_dir: /app

  web:
    image: nginx:alpine
    ports:
      - "8080:80" # Host -> Container
    volumes:
      - ./app:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php